### ISSUE TITLE
Mismatch in number of electrodes for 798

### ISSUE THREAD

**Issue by hvgazula** [hassonlab/247-preprocessing#14]
@baubrey In matlab format there are 192 electrodes whereas EDF has 205. Going forward, will all 205 be used or are there electrodes that need to be ignored?

**Comment by baubrey** [comment]
EDF has 205 channels, 192 of which are electrode signals. 
`self.non_electrode_id = ["SG", "EKG", "DC"]` in the init function of Ecog class points to which channels are not electrodes. (I might move this to Config).

**Comment by hvgazula** [comment]
I see. Are those 3 non-electrodes or electrodes that start with either of the three? Trying to understand the (205-192) = 13 - 3 = 10.

**Comment by baubrey** [comment]
Channel labels that have any of those 3 letter codes are not electrode channels. For 798 these are:`'SG1', 'SG2', 'SG3', 'SG4', 'SG5', 'SG6', 'EKG1', 'EKG2', 'DC1', 'DC2', 'DC3', 'DC4', 'DC5'`

**Comment by hvgazula** [comment]
Thanks Bobbi. 🙏
